# Generated by Django 2.2 on 2021-06-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210619_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='nome_do_consultor',
            field=models.CharField(max_length=255),
        ),
    ]
