# Generated by Django 2.2 on 2021-06-19 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210619_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='nome_do_consultor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
